continue

diff --git a/bin/nemesis b/bin/nemesis
--- a/bin/nemesis
+++ b/bin/nemesis
@@ -2,16 +2,70 @@
 
 # ---------------------------------------------
 # Created by Statemood, 2014-04-02, 17:50
-# Updated by Statemood, 2014-04-02, 18:00
+# Updated by Statemood, 2014-04-04, 10:00
 #            Statemood@gmail.com
 #
 # Project Nemesis:
 #         https://github.com/Statemood/Nemesis
 # ---------------------------------------------
 
-Source="$1"
+READFILE="$1"
+APPSNAME="$(basename $0)"
+LOCKEDIP="/dev/shm/$APPSNAME/Locked.ip"
+RULEFILE="/dev/shm/$APPSNAME/Rules.list"
+LOG_FILE="/data/log/$APPSNAME/$APPSNAME.log"
+IPTABLES="/sbin/iptables"
 
-while read line
+if [ ! -f "$READFILE" ]
+then
+    echo -e "Error: $READFILE: File not found"
+    exit 1
+fi
+
+#. $RULEFILE || exit 1
+tail -f $READFILE | while read line
 do
-    action
+       date=`echo $line | awk '{print $4}' | sed -e 's/T/ /' -e 's/+08:00//'`
+       time=`echo $date | awk '{print $2}'`
+       date=`echo $date | awk '{print $1}'`
+     ipaddr=`echo $line | awk '{print $1}'`
+     status=`echo $line | awk '{print $5}'`
+     method=`echo $line | awk '{print $7}' | sed 's/"//'`
+    request=`echo $line | awk '{print $8}'`
+    referer=`echo $line | awk '{print $10}'`
+    
+    # Define rules here:
+    # test ! match && continue
+    
+
+    ipstr="`grep $ipaddr $LOCKEDIP`"
+    if [ "X$ipstr" = "X" ]
+    then
+        $IPTABLES -I INPUT -p tcp -s $ipaddr --dport 80 -j ATTACK
+        echo -e "`date +'%F %T'` IP=$ipaddr\t STATUS=LOCKED\t TIMES=1" >> $LOCKEDIP
+    else
+        locktime=`echo $ipstr | awk '{print $2}'`
+        locktime=`date -d "$locktime" +%H%M%S`
+        lockstat=`echo $ipstr | awk -F 'STATUS=' '{print $2}'`
+        ip_count=`echo $ipstr | awk -F 'Times='  '{print $2}'`
+
+        if   [ "$ip_count" -ge 1 ]
+        then
+            unlockmin=15
+        elif [ "$ip_count" -ge 5 ]
+        then
+            unlockmin=30
+        elif [ "$ip_count" -ge 10 ]
+        then
+            unlockmin=45
+        fi
+               
+        relesetime=`date -d "$unlockmin" +%H%M%S`
+        if [ "$locktime" -ge "$unlockmin" ]
+        then
+            $IPTABLES -D INPUT -p tcp -s $ipaddr --dport 80 -j ATTACK
+            sed -i "/IP=$ipaddr/d" $LOCKEDIP
+            echo -e "`date +'%F %T'` IP=$ipaddr\t STATUS=RELEASED\t TIMES=$((ip_count++))" >> $LOCKEDIP
+        fi
+    fi
 done
